# My App Configurations
mapName.PersonProfile = entityPersonProfile
collectionName.PersonProfile = person_profile

mapName.WaContactProfile = entityWaContactProfile
collectionName.WaContactProfile = wa_contact_profile

mapName.WaMessage = entityWaMessage
collectionName.WaMessage = wa_message