# My App Configurations
myApp.hazelcast.PersonProfile.mapName = entityPersonProfile
myApp.hazelcast.PersonFact.mapName = entityPersonFact

myApp.hazelcast.WaContactProfile.mapName = entityWaContactProfile
myApp.hazelcast.WaMessage.mapName = entityWaMessage