quarkus.http.host=0.0.0.0
quarkus.http.port=80

# MongoDB Configuration
quarkus.mongodb.hosts = localhost:27017
quarkus.mongodb.database = db_hzc_mapstore
quarkus.mongodb.credentials.username = admin
quarkus.mongodb.credentials.password = admin
quarkus.mongodb.credentials.auth-source = admin

# Hazelcast Client Configuration
quarkus.hazelcast-client.cluster-name=dev
quarkus.hazelcast-client.cluster-members=localhost:5701

# Indica que o PersonMapStore será usado para a estrutura de dados 'persons'
quarkus.hazelcast-client.map.BsonPerson.map-store.implementation=BsonPersonMapStore
quarkus.hazelcast-client.map.BsonPerson.map-store.write-delay-seconds=12