quarkus.http.host=0.0.0.0
quarkus.http.port=80

# Hazelcast Client Configuration
#quarkus.hazelcast-client.cluster-name=dev
#quarkus.hazelcast-client.cluster-members=localhost:5701
#quarkus.hazelcast-client.connection-timeout=5000

quarkus.log.category."com.hazelcast".level=DEBUG

# My App Configurations
mapName.PersonProfile = entityPersonProfile
mapName.PersonFact = entityPersonFact
mapName.WaMessage = entityWaMessage