quarkus.http.host=0.0.0.0
quarkus.http.port=80

quarkus.log.category."com.hazelcast".level=DEBUG

# My App Configurations
mapName.PersonProfile = entityPersonProfile
mapName.PersonFact = entityPersonFact
mapName.WaMessage = entityWaMessage